#!/bin/bash
#Hitokiri
#2010
help="
Kullanım: wiki-editor [DOSYA]...
Yardım: wiki-editor [Seçenek] ....
Seçenekler:
-v,--version , 	Versiyon bilgisini yazar ve çıkar..
-d ,--debug , 	Hata kayıtlarını log dosyasına yazın 
		log dosyasına ulaşmak için
		nano  ~/.config/wiki-editor.log komutunu kullanabilirsiniz.
-k ,--kısayol , Programda kullanılan tuş kombinasyonlarını öğrenin..	
-l,--lisans, 	Lisans bilgisini almak için.
-h,--help ,	Yardım seçenekleri için inceleyin..
--help-all , 	Tüm belgeyi okuyun..
"

Lisans=$(cat pyler/araclar.py|sed -n '123,132p')

ksayol=$(cat pyler/araclar.py|sed -n '273,293p')

dizin='./pyler'
#mkdir -p ~/.gconf/apps/wiki-editor/
# touch -a ~/.gconf/apps/wiki-editor/%gconf.xml  
#if [ "`(grep $ ~/.gconf/apps/wiki-editor/%gconf.xml -c )`" -ne "24" ];then
#	python $dizin/default_conf.py
#fi 
while test $# -gt 0 ; do
  case $1 in
    -h | --help)       
      echo "$help"
      exit $?
      ;;
    -v |--version)
      echo "Wiki Editor 1.9"
      exit $?
      ;;
      -k |--kısayol)
      echo "$ksayol"
      exit $?
      ;; 
      -d |--debug)                        
      date|tee -a /tmp/wiki-editor.log
      cd "$dizin" ; python3 ./wiki_editor.py  2>&1 |tee -a /tmp/wiki-editor.log
      exit $?
      ;;
    -l | --lisans)                        
      echo "$Lisans"
      exit $?
      ;;
    --help-all)                        
      echo "$help$ksayol$Lisans" 
      exit $?
      ;;      
    --)                 
      echo "Bilinmeyen seçenek."       
      shift
      break
      ;;
    -*)                      
      echo "$help"
      exit 1
      ;;
    /*)
      cd "$dizin" ; python3 ./wiki_editor.py   "$1"
      exit 1
      ;;
     *)
      cd "$dizin" ; python3 ./wiki_editor.py   "$*"
      exit 1
      ;;     	 
  esac
done
cd "$dizin" ; python3 ./wiki_editor.py
